name: Coverage

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Code Coverage
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build and run coverage
      run: |
        npm install
        npm run build
        npm run coverage
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./coverage/clover.xml #optional
