name: NPM Publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: Build and publish
        run: |
          npm install
          npm version --tag from-git
          npm run build
          npm publish -f
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}